# Site settings
title: Brandon Kang
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Brandon Kang
user_description: I'm an aspiring data scientist and incoming data science intern at Roblox! Graduating from Georgia Tech this Spring 2020 in Industrial Engineering, I plan to attend graduate school in the Fall for Analytics. I also founded and currently lead Seoulstice, a K-Pop dance team that has won at competitions and perform for over 15 events every year!
user_title: Data Science
email: brandonkang00@gmail.com
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src']
